### PR TITLE
fix(kebab menu): Enable Move to Backlog functionality. Fixes #1499

### LINKED ISSUE #1499: Move to backlog opens details view on board
http://www.screencast.com/t/3D151ltSL31

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Enable Move to Backlog option on list view and backlog view
Add toast notification for Move to Backlog success and failure
This fixes #1499.

Existing issue:
Update of count in backlog (+1) and selected iteration (-1) does not happen
Update of list does not happen

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

File: src/app/work-item/work-item-board/work-item-board.component.ts [hunk 1]
```diff
@@ -353,8 +354,35 @@ export class WorkItemBoardComponent implements OnInit, OnDestroy {
   }
 
   onMoveToBacklog(event: any): void {
-    alert('Not Implemented yet');
     event.stopPropagation();
+    //set this work item's iteration to None
+    //send a patch request
+    this.workItem.relationships.iteration = {}
```
Comment (vikram-raj) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: So, are we going to unassociated the iteration from the WI or associate it with root iteration?

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

File: src/app/work-item/work-item-board/work-item-board.component.ts (hunk 1 above)
Comment (nimishamukherjee) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: @vikram-raj this implementation was done assuming sending iteration as {} will map it to the root iteration.

Comment (vikram-raj) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: @nimishamukherjee Ok.

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

File: src/app/work-item/work-item-board/work-item-board.component.ts (hunk 1 above)
Comment (nimishamukherjee) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: Pasting Mattermost chat:
> 
nimisha 
5:05 PM @michaelkleinhenz (pandora's box) on the kebab menu for Move to Backlog - what do I set the iteration as {} or root 

michaelkleinhenz 
5:07 PM @nimisha {} should work to set the iteration to root.
5:08 PM @nimisha so "iteration: {}", not "iteration: {data: {}}"
5:08 PM @nimisha if it is not working, it is a bug in the core.

Core task to handle empty iteration - https://github.com/almighty/almighty-core/issues/1185

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1675-fabric8-planner.int.rdu2c.fabric8.io
