### PR TITLE
Clear work-item selection after closing detail-box

### LINKED ISSUE #1554: WI selection should be cleared on close of workItem-detail-box
Steps to reproduce
1. Click on any workitem
2. Notice that it is selected (background is blue) & detail-box is opened from right side
3. Close the detail-box by clicking X
4. notice that WI is still selected.

Need to clear selected item.

Same for board view items.

### PR DESCRIPTION
**Pull request by pranavgore09**
Fixes #1554 

New event `detail_close` is fired when we close the work item detail box. That helps us in clearing the work item selection.

I could see event name strings of both types e.g> `updateWorkItem` vs `update_work_item_hierarchy`.
Let me know if event name should be changed to camelCase or snake_case is fine :)

### CODE REVIEW

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1575.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1575.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1575.int.rdu2c.fabric8.io

File: src/app/work-item/work-item-board/work-item-board.component.ts [hunk 1]
```diff
@@ -367,6 +367,13 @@ export class WorkItemBoardComponent implements OnInit, OnDestroy {
             this.changeLane(data[0].oldState, data[0].newState, data[0].workItem);
       })
     );
+
+    this.eventListeners.push(
+      this.broadcaster.on<string>('detail_close')
+      .subscribe(()=>{
+        this.workItem = <WorkItem>{};
```
Comment (nimishamukherjee) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: What does this do?

Comment (pranavgore09) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: @nimishamukherjee  : It will reset `this.workItem`. It will keep the type as `WorkItem` but value is `empty`.
