### PR TITLE
fix(board view): Display newly added work item, added via the detailed view, in the board view. Fixes #1496.

### LINKED ISSUE #1496: Creating a new work item board view doesn't show up
http://www.screencast.com/t/rMBJ3lChHqr

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Display newly added work item, added via the detailed view, in the board view. Fixes #1496.

### CODE REVIEW

File: src/app/work-item/work-item-board/work-item-board.component.ts [hunk 1]
```diff
@@ -90,6 +90,11 @@ export class WorkItemBoardComponent implements OnInit, OnDestroy {
     private areaService: AreaService,
     private filterService: FilterService,
     private route: ActivatedRoute) {
+      router.events.subscribe(event => {
```
Comment (sanbornsen) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: * I believe, every time you open the details page this will trigger even if you are not adding a new item. In fact on every navigation the list will re load with this chunk of code.  
* Also it's not being unsubscribed anywhere, so that could cause a event leakage.

Comment (sanbornsen) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: I strongly feel there is a better way to do this, let me figure out.

Comment (nimishamukherjee) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: The challenge is the detail view is a router outlet so we cannot bind any listener.
If you see work-item-board.component.html > <alm-work-item-quick-add
(workItemCreate)="onCreateWorkItem($event)" takes care of updating the lane.

Comment (sanbornsen) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: I understand, but still no playing with routers anywhere, other than filtering and querying. Instead, we can use workitemService. We can keep a BehaviorSubject in work item service and any component like board can watch over it for update or add item.

Comment (sanbornsen) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: Also we need this feature matching with the current filter to the page. Right?

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1721-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
[test]

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1721-fabric8-planner.int.rdu2c.fabric8.io

File: src/app/work-item/work-item-board/work-item-board.component.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ import {
   ViewEncapsulation
 } from '@angular/core';
 import { Response } from '@angular/http';
-import { Router, ActivatedRoute } from '@angular/router';
+import { NavigationEnd, Router, ActivatedRoute } from '@angular/router';
```
Comment (sanbornsen) [inline src/app/work-item/work-item-board/work-item-board.component.ts]: **NavigationEnd** should not be needed anymore.

File: src/app/work-item/work-item.service.ts [hunk 3]
```diff
@@ -687,6 +692,18 @@ export class WorkItemService {
   }
 
   /**
+   * Usage: This method emit a new work item created event
+   * The list view and board view listens to this event
+   * and updates the view based on applied filters.
+   */
+
+  emitAddWI(workItem: WorkItem) {
+    if(this.filterService.doesMatchCurrentFilter(workItem)){
```
Comment (sanbornsen) [inline src/app/work-item/work-item.service.ts]: This is okay, but think, now work item service has a dependency on filter service. We can have it in the component. No matter what item it is, it should be emitted and then from the component we check if the item matches current filter or not.
Also, we can use the same observer in other places where filter doesn't matter.

File: src/app/shared/filter.service.ts [hunk 4]
```diff
@@ -10,6 +10,8 @@ import { HttpService } from './http-service';
 
 import { FilterModel } from '../models/filter.model';
 
+import { WorkItem } from '../models/work-item';
```
Comment (sanbornsen) [inline src/app/shared/filter.service.ts]: This is a direct dependency to WorkItem module, we don't need the type here, do we?

File: src/app/work-item/work-item.service.spec.ts [hunk 5]
```diff
@@ -234,10 +237,11 @@ describe('Work Item Service - ', () => {
   });
 
   beforeEach(inject(
-    [WorkItemService, MockBackend, IterationService, AreaService],
-    (service: WorkItemService, mock: MockBackend, iService: IterationService, aService: AreaService) => {
+    [WorkItemService, MockBackend, FilterService, IterationService, AreaService],
```
Comment (sanbornsen) [inline src/app/work-item/work-item.service.spec.ts]: Now, do we need **FilterService** in the spec anymore?

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1721-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1721-fabric8-planner.int.rdu2c.fabric8.io
